version: "3"
services:
  db:
    image: postgres:11.6
    container_name: task_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=default
      - TZ=Asia/Tokyo
    volumes:
      - dev-vol:/var/lib/postgres/data
      - ../.data/task_db:/var/lib/postgres/data:cached
      - ./task_db:/docker-entrypoint-initdb.d:cached

  api:
    container_name: task_api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    environment:
      - WATCHFILES_FORCE_POLLING=true

  web:
    container_name: task_web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    user: 1000:1000
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./web/task_vue:/app # package.json のある場所
      - dev-vol:/web/task_vue
    ports:
      - "3000:3000"

volumes:
  dev-vol:
  api_env:
    driver: local
  web_env:
    driver: local
  db_data:
    driver: local
